# Pentagon Numbers
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
# is minimised; what is the value of D?


def pentagonal_number(n):
    return int(n * (3 * n - 1) / 2)


pentagonal_numbers = [pentagonal_number(n) for n in range(1, 10000)]
for i in range(0, 9999):
    for j in range(i + 1, 9999):
        if pentagonal_numbers[j] - pentagonal_numbers[i] in pentagonal_numbers and pentagonal_numbers[j] + \
                pentagonal_numbers[i] in pentagonal_numbers:
            print("{} + {} = {}".format(pentagonal_numbers[j], pentagonal_numbers[i],
                                        pentagonal_numbers[j] + pentagonal_numbers[i]))
            print("{} - {} = {}".format(pentagonal_numbers[j], pentagonal_numbers[i],
                                        pentagonal_numbers[j] - pentagonal_numbers[i]))
            break
