# Triangular, pentagonal, and hexagonal
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	    Tn=n(n+1)/2 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	    Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
import math
from Problem_42 import triangle_number

def is_triangle_number(n):
    N = (1 + math.sqrt(8 * n + 1)) / 2
    return N == int(N)


def is_pentagonal_number(n):
    N = (1 + math.sqrt(24 * n + 1)) / 6
    return N == int(N)


def is_hexagonal_number(n):
    N = (1 + math.sqrt(8 * n + 1)) / 4
    return N == int(N)


if __name__ == '__main__':
    n = (1 + math.sqrt(8 * 40755 + 1)) / 2 + 1
    while True:
        N = triangle_number(n)
        if is_pentagonal_number(N) and is_hexagonal_number(N):
            print(N)
            break
        n += 1

